services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    expose:
      - "80"
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
